/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DropPanel.java
 *
 * Created on 21.09.2010, 10:46:53
 */

package de.uni_hamburg.corpora.swing;

import javax.swing.ImageIcon;

/**
 *
 * @author thomas
 */
public class DropPanel extends javax.swing.JPanel {

    /** Creates new form DropPanel */
    public DropPanel() {
        initComponents();
    }

    public void setIcon(ImageIcon icon){
        jLabel1.setIcon(icon);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(15, 155, 155));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(), "Drop corpus files here:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        setToolTipText("Drag corpus files here.");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/droptarget.png")));
        jLabel1.setToolTipText("Drag corpus file(s) here");
        add(jLabel1);
    }// </editor-fold>//GEN-END:initComponents       


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
